In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.3.0


In [3]:
#tensor is essential a n-dimensional array
hello = tf.constant("Hello ")

In [4]:
world = tf.constant("World")

In [5]:
#hello is a tensor
type(hello)

tensorflow.python.framework.ops.Tensor

In [6]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [8]:
#to actuallyg print, need a session
with tf.Session() as sess:
    result = sess.run(hello+world)

In [9]:
#b because of python 3
print(result)

b'Hello World'


In [10]:
a = tf.constant(10)

In [12]:
b = tf.constant(20)

In [13]:
type(a)

tensorflow.python.framework.ops.Tensor

In [14]:
a+b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [15]:
#tensor flow keeping track how many times we run this
a+b

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [16]:
a+b

<tf.Tensor 'add_4:0' shape=() dtype=int32>

In [18]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [19]:
result

30

In [20]:
const = tf.constant(10)

In [21]:
fill_mat = tf.fill((4,4),10)

In [22]:
myzeros = tf.zeros((4,4))

In [23]:
myones = tf.ones((4,4))

In [24]:
myrandn = tf.random_normal((4,4),mean=0,stddev=1.0)

In [25]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [26]:
myzeros

<tf.Tensor 'zeros:0' shape=(4, 4) dtype=float32>

In [27]:
myones

<tf.Tensor 'ones:0' shape=(4, 4) dtype=float32>

In [28]:
myrandn

<tf.Tensor 'random_normal:0' shape=(4, 4) dtype=float32>

In [30]:
myops = [const,fill_mat,myones,myzeros,myrandn,myrandu]

In [31]:
sess = tf.InteractiveSession()

In [33]:
for op in myops:
    print(sess.run(op))
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


[[-0.10963301 -0.59120977  0.66395843  0.16414763]
 [ 1.20940638  2.35760069  0.40354502 -0.1066587 ]
 [-0.12587816  0.67948431 -1.31598806  1.09940517]
 [ 0.56542611  1.30468786  0.12520806  0.12351275]]


[[ 0.89519429  0.77475131  0.27452052  0.30021799]
 [ 0.97039902  0.11743188  0.12129331  0.52996242]
 [ 0.86647511  0.92299974  0.68996644  0.69525576]
 [ 0.99254572  0.63678372  0.94192803  0.73422909]]




In [36]:
a = tf.constant([[1,2],
                [3,4]])

In [37]:
b = tf.constant([[10],[100]])

In [38]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [39]:
result = tf.matmul(a,b)

In [40]:
sess.run(result)

array([[210],
       [430]])

In [41]:
result.eval()

array([[210],
       [430]])